return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 13,
  nextobjectid = 23,
  backgroundcolor = { 0, 0, 0 },
  properties = {},
  tilesets = {
    {
      name = "castle_cardcastle",
      firstgid = 1,
      filename = "../tilesets/castle_cardcastle.tsx",
      exportfilename = "../tilesets/castle_cardcastle.lua"
    },
    {
      name = "castle_throneroom",
      firstgid = 145,
      filename = "../tilesets/castle_throneroom.tsx",
      exportfilename = "../tilesets/castle_throneroom.lua"
    },
    {
      name = "castle_town_bg",
      firstgid = 235,
      filename = "../tilesets/castle_town_bg.tsx",
      exportfilename = "../tilesets/castle_town_bg.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "tiles",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0,
        0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0,
        0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0,
        0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0,
        0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0,
        0, 0, 0, 0, 13, 14, 14, 5, 4, 14, 14, 15, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 7, 9, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 7, 9, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 7, 9, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 7, 9, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "objects_tiles_deco",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          class = "",
          shape = "rectangle",
          x = 180,
          y = 150,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 220,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          class = "",
          shape = "rectangle",
          x = 220,
          y = 150,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 221,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          class = "",
          shape = "rectangle",
          x = 260,
          y = 150,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 222,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          class = "",
          shape = "rectangle",
          x = 180,
          y = 190,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 226,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          class = "",
          shape = "rectangle",
          x = 260,
          y = 190,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          class = "",
          shape = "rectangle",
          x = 260,
          y = 230,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 234,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          class = "",
          shape = "rectangle",
          x = 180,
          y = 230,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 232,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          class = "",
          shape = "rectangle",
          x = 220,
          y = 230,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 233,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          class = "",
          shape = "rectangle",
          x = 220,
          y = 190,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 227,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          class = "",
          shape = "rectangle",
          x = 390,
          y = 180,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 179,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          class = "",
          shape = "rectangle",
          x = 430,
          y = 180,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 180,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          class = "",
          shape = "rectangle",
          x = 410,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 186,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          class = "",
          shape = "rectangle",
          x = 210,
          y = 70,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          class = "",
          shape = "rectangle",
          x = 320,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          class = "",
          shape = "rectangle",
          x = 370,
          y = 300,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          class = "",
          shape = "rectangle",
          x = 270,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          class = "",
          shape = "rectangle",
          x = 190,
          y = 290,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 19,
          name = "npc",
          class = "",
          shape = "rectangle",
          x = 300,
          y = 90,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 286,
          visible = true,
          properties = {
            ["actor"] = "castle_lancerpainting",
            ["script"] = "castle_room_lancer_painting"
          }
        },
        {
          id = 20,
          name = "npc",
          class = "",
          shape = "rectangle",
          x = 340,
          y = 90,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 286,
          visible = true,
          properties = {
            ["actor"] = "castle_lancerpainting",
            ["script"] = "castle_room_lancer_painting"
          }
        },
        {
          id = 21,
          name = "npc",
          class = "",
          shape = "rectangle",
          x = 380,
          y = 90,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 286,
          visible = true,
          properties = {
            ["actor"] = "castle_lancerpainting",
            ["script"] = "castle_room_lancer_painting"
          }
        },
        {
          id = 22,
          name = "npc",
          class = "",
          shape = "rectangle",
          x = 420,
          y = 90,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 286,
          visible = true,
          properties = {
            ["actor"] = "castle_lancerpainting",
            ["script"] = "castle_room_lancer_painting"
          }
        }
      }
    }
  }
}
